name: ukb_env
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.9
    - pandas
    - numpy
    - scikit-learn
    - r-base=4.4.1
    - r-desctools
    - r-stringr
    - r-proc
    - r-domc
    - r-dplyr
    - r-data.table
    - r-glmnet
    

