name: ukb_env
channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    - python=3.9
    - matplotlib
    - pandas
    - plink
    - numpy=1.26
    - scikit-learn
    - statsmodels
    - shap
    - openpyxl
    - plotly
    - seaborn
    - pip
    # R and R packages
    - r-base=4.3.*
    - r-glmnet
    - r-data.table
    - r-dplyr
    - r-domc
    - r-proc
    - r-desctools
    - r-stringr
    - r-argparse
    - pip:
        - fasttreeshap
        - ipython
        - xgboost
        - matplotlib-venn
    

